name: PR10      
on: push            
jobs:
    ONEJOB:
        runs-on: windows-latest    
        steps:
             - name: Checkout
               uses: actions/checkout@v5.0.0

             - name: RUN
               run: dotnet run